name: Docker Compose CI

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Compile Discord Dependencies
        run: |
          cd discord/
          cargo build --release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services
        run: docker-compose build

      - name: Run Docker Compose services
        run: docker-compose up --detach
