name: Docker Compose CI

run-name: Docker Compose CI | ${{ github.event_name == 'push' && split(github.event.head_commit.message, '\n')[0] || github.event_name == 'pull_request' && github.event.pull_request.title }} by ${{ github.actor }} on '${{ github.ref_name }}'

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Generate Cargo.lock
        run: |
          cd discord/
          cargo generate-lockfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services
        run: docker-compose build

      - name: Run Docker Compose services
        run: docker-compose up --detach
