name: Node.js CI

run-name: Node.js CI | ${{ github.event_name == 'push' && split(github.event.head_commit.message, '\n')[0] || github.event_name == 'pull_request' && github.event.pull_request.title }} by ${{ github.actor }} on '${{ github.ref_name }}'

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    defaults:
      run:
        working-directory: ./twitch
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./twitch/package-lock.json"
      - run: npm ci
      - name: Check for Build
        run: npm run build --if-present
      - name: Run Tests
        run: npm test
